### ISSUE TITLE
Submit command button

### ISSUE THREAD

**Issue by Saacy** [JustArchiNET/ASF-ui#188] opened 2018-11-24 20:55 UTC
Hello.
Please add submit button to the commands page (mb ui configuration option?).
At the moment there is no way to send command from some devices.
Thank you!

**Comment by Aareksio** [comment] 2018-11-24 21:18
What devices precisely?

**Comment by Abrynos** [comment] 2018-11-24 21:19
phones

**Comment by Aareksio** [comment] 2018-11-24 21:44
What phones exactly?
![phone ss](https://yko.im/bZyM.png)

**Comment by Abrynos** [comment] 2018-11-24 21:44
can't do it on my Huawei P10 Lite

**Comment by Aareksio** [comment] 2018-11-24 22:13
I have tested on 
- LG G6
- Apple Iphone 8
- Xiaomi Mi 6, Mi 4c, Mi a2
- Huawei Mate 10 
- Samsung s8

Though, on some shitty stock browser on Xiaomi Mi 6, you have to click the keyboard's "send" button twice.

Phones from all major manufacturers have no problem handling the input properly, on top of that, I can't think of a button fitting the design there. Issue may stay open and PR with such feature is welcomed, but I don't plan on implementing.

[Minimal reproduction for testing](https://codepen.io/anon/pen/wQjNNL)

**Comment by Aareksio** [comment] 2018-12-06 20:11
Possibly fixed in 8049b4ce7bb931a6d09cd965108ec17022fa8b51

**Comment by MrBurrBurr** [comment] 2018-12-16 16:02
@Saacy 
Can you confirm that it was fixed in 8049b4ce7bb931a6d09cd965108ec17022fa8b51?

**Comment by MrBurrBurr** [comment] 2019-01-05 00:14
Closed due to inactivity.

**Closed by MrBurrBurr** 2019-01-05 00:14 UTC
Labels: Feedback welcome, Requires more info
