### ISSUE TITLE
Add option to send error reports

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#131] opened 2018-11-08 05:16 UTC
Once we have UI configuration view available we should add an option to automatically send error reports. Default value should be `false`

**Comment by JustArchi** [comment] 2018-11-08 05:17
I'd rather prefer option to generate error log that user can post on GitHub, something like debug mode from ASF.

**Comment by Aareksio** [comment] 2018-11-08 11:05
I find it utterly stupid not to report automatically and rely on user in this manner, **but** generating such log sounds somehow interesting and I never done it before, so may implement for fun as well.

~Once it's done, smuggling auto reporting code won't be too hard too 🤔~

**Comment by Aareksio** [comment] 2018-11-08 11:51
Last time I checked it's 2018, we do not bother humans with tasks that can be easily done better automagically.

Reporting reproduction steps along with application's state wouldn't be a problem. Neither would be attaching a screenshot (or video) for visual bugs. Of course these couldn't be sent by default, rather just from one browser, once the error have been marked as requiring such information.

Whether you like it or not, multiple apps do this already, because their job, along with fulfilling clients' needs, is to serve seamless expirience.

We are not debating adding automatic reporting here, as it already been rejected. I'm just clarifying that the motivations presented in your comment do not stand.

**Closed** 2018-11-09 09:09 UTC
Labels: Status: Work In Progress, Type: Improvement
