### ISSUE TITLE
Error, You have to enter a name

### ISSUE THREAD

**Issue by rossiscool123** [JustArchiNET/ASF-ui#1472] opened 2021-07-13 13:32 UTC
## Description
"Error, You have to enter a name" when creating a bot.
![20210713143103](https://user-images.githubusercontent.com/62076535/125460685-ca89febf-4a3b-4039-8769-fc5820e15ec3.png)

## Steps to reproduce
Open the ASF IPC web UI and try and create a bot.

## Expected behavior
Bot to be created and running.

## Current behavior
You'll get an error prompting you to name the bot even though it has been named.

**Comment by Abrynos** [comment] 2021-07-13 13:41
This is a duplicate of [issue 1460](https://github.com/JustArchiNET/ASF-ui/issues/1460) and [discussion 2358](https://github.com/JustArchiNET/ArchiSteamFarm/discussions/2358).

It is already fixed and you can apply the fix by either:
- downloading the latest build of ASF-ui from [here](https://github.com/JustArchiNET/ASF-ui/actions/runs/1026277827) and placing the contents inside the `www` folder of your installation of ASF.
- changing the `UpdateChannel` of your ASF to `Experimental` and thus updating ASF to the latest pre-release (this is only recommended to users that *know* what they are doing).
- waiting for the next ASF release to go stable.

I personally would recommend the first option.

**Closed** 2021-07-13 13:43 UTC
Labels: 🐛 Bug, 👥 Duplicate, 🟢 Low priority

**Comment by rossiscool123** [comment] 2021-07-13 14:53
@Abrynos Thank you, I did try looking for the issue on the repo but I'm not too familiar with GitHub so applogies. Thanks anyway.
