### ISSUE TITLE
ASF-ui (still) can't handle updates of itself

### ISSUE THREAD

**Issue by JustArchi** [JustArchiNET/ASF-ui#1411] opened 2021-06-03 22:31 UTC
https://steamcommunity.com/groups/archiasf/discussions/1/3112530528185380911/

https://steamcommunity.com/groups/archiasf/discussions/1/4477100383816836572/

https://github.com/JustArchiNET/ArchiSteamFarm/discussions/2334

And the issues keep popping up. Even more on discord that I'm too lazy to link.

**Comment by MrBurrBurr** [comment] 2021-06-04 23:37
@Aareksio Any input on this? I am lost here.

**Comment by MrBurrBurr** [comment] 2021-06-06 02:32
This issue seems to be a duplicate of https://github.com/JustArchiNET/ASF-ui/issues/1330#issuecomment-813850742

**Closed by MrBurrBurr** 2021-06-06 02:32 UTC
Labels: 🐛 Bug, 💢 No solution yet, 🔴 High priority
