### ISSUE TITLE
ASF-UI is not showing the balance preview, on the bots card, in the graphical interface.

### ISSUE THREAD

**Issue by darkdroider** [JustArchiNET/ASF-ui#1654] opened 2023-12-19 14:16 UTC
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest stable release

### ASF-ui version

b924e3b

### Bug description

This error happened a few years ago, and it was very simple to resolve. I don't know if there were any changes. Thanks

### Expected behavior

![before](https://github.com/JustArchiNET/ASF-ui/assets/64504631/49b39a98-3e27-439d-80ae-bf46c8822843)

### Actual behavior

![now](https://github.com/JustArchiNET/ASF-ui/assets/64504631/1b63a794-4493-4578-8b73-06fbfd0f8cd8)

### Steps to reproduce

Just click on any bot, on ASF-UI

### Can you help us with this bug report?

No, I don't have time, skills or willings for any of that

**Comment by MrBurrBurr** [comment] 2023-12-20 01:15
Closing because its a duplicate of https://github.com/JustArchiNET/ASF-ui/issues/1653

This bug has already been fixed in https://github.com/JustArchiNET/ASF-ui/commit/a2e081a241b9f664ed34357eb0b253429c200034

**Closed by MrBurrBurr** 2023-12-20 01:15 UTC
Labels: 🐛 Bug, 🧐 Evaluation
