### ISSUE TITLE
Don't call rename endpoint when user doesn't change name

### ISSUE THREAD

**Issue by deluxghost** [JustArchiNET/ASF-ui#468] opened 2019-02-23 04:39 UTC
## Description
why have another http request if user didn't change botname?

## Steps to reproduce
go to config page of a bot, save it

## Expected behavior
only call rename when user changes the name

**Comment by JustArchi** [comment] 2019-02-23 04:40
Better question is why ASF doesn't throw 400 on you yet.

**Comment by JustArchi** [comment] 2019-02-23 04:40
Oh no, wait, it does, I took that into account already, yes! 🎉

**Comment by MrBurrBurr** [comment] 2019-02-23 11:02
It should already only send rename request if the user changed the name, as you can see [here](https://github.com/JustArchiNET/ASF-ui/blob/master/src/views/modals/BotConfiguration.vue#L137).

I will take a look later.

**Comment by MrBurrBurr** [comment] 2019-02-23 11:25
Yeah as expected, I can't reproduce on master branch.

**Comment by deluxghost** [comment] 2019-03-08 06:53
it still call rename endpoint in 1.0.8, with empty payload `{}`, even if i just do nothing in config pane and save

resp:

```
{"errors":{"":["Required property 'NewName' not found in JSON. Path '', line 1, position 2."]},"title":"One or more validation errors occurred.","status":400,"traceId":"<idk what this id does, since it says trace so i prefer hide it>"}
```

**Comment by deluxghost** [comment] 2019-03-08 07:20
good, i see the reason.

when you rename from asf-ui successfully, asf-ui write a new property named `Name` into the config file.

and asf-ui will think this is the botname and set it as the textbox placeholder in config panel, but no, this way is wrong, the actually name is the key in json, asf doesn't have a property named `Name`.

now a bot `A` can have `"Name": "B"` results in asf-ui shows Name B in config panel

if you want to reproduce this, check the bot config files and remove the Name entry.

so:

1. dont save a `Name` into files
2. dont read such property as botname, use the actually name instead (the key in json)

request to reopen this issue

**Comment by deluxghost** [comment] 2019-03-08 08:48
my post from discord, just FYI:

> deluxghost: changing bot to bot1
> deluxghost: and the saving request set "Name"
> deluxghost: not by rename endpoint
> deluxghost: asf wont remove unknown property, right?
> deluxghost: and it was written to file
> deluxghost: then when asf-ui get bot info, the "Name" will appear in botconfig
> deluxghost: request of POST /api/bot/bot
> ![](https://cdn.discordapp.com/attachments/267292556709068800/553494785998979072/unknown.png)
> deluxghost: response of /api/bot/asf
> ![](https://media.discordapp.net/attachments/267292556709068800/553494989125189633/unknown.png)
> deluxghost: the real name is the keyname "bot1", not the "Name: bot1" which was saved wrongly
> ![](https://media.discordapp.net/attachments/267292556709068800/553495759409119233/unknown.png)
> deluxghost: i think there is nothing to do on asf side
> deluxghost: > the "Name" property is added by ASF in response and should match file name
> asf is already provide the botname in keyname, the Name in response was added by ui's post request

**Comment by JustArchi** [comment] 2019-03-08 14:49
I don't know why you didn't catch this earlier, you can have a really crazy fuckup now, since ASF will now save `Name` into the botconfig, and if you rename it then you'll have a fucked up ASF response next, where `newBotName` will be key, with config included `Name: oldBotName` in it.

You can't just throw random shit at API and assume that it's fine 🤔.

**Comment by Aareksio** [comment] 2019-03-08 15:30
In case anyone wonders, it's done [here](https://github.com/JustArchiNET/ASF-ui/blob/master/src/views/modals/BotConfiguration.vue#L113-L125). After first configuration edit via asf-ui versions including this block, the config included new property `Name`, which overrides the _custom field_.

I suggest reverting 9e2e843b17554e22bd9a95a07e83fbf93e86087e for now and throwing a little less random features into the build without consideration, because despite the popular belief, even the _least complicated_ but not thought over stuff adds a lot to overall complexity and makes detecting bugs harder.

The rename feature may be added later, after we figure out how to integrate it with the whole experience in a way not breaking existing functionality.

**Comment by JustArchi** [comment] 2019-03-08 15:39
@Aareksio reverting rename endpoint will not fix the same issue in config endpoint (and probably in a lot of other endpoints), where you shouldn't write name property in the request to begin with.

**Comment by Aareksio** [comment] 2019-03-08 16:19
We're sending this property in addition, because it is appended to our bot config model - it was changed to be this way in the commit I pointed to, precisely in the lines I also pointed to.

Other than that, we're sending exactly the same properties we get, so it should be alright (and is to my knowledge).

It won't fix the issue retroactively, so people who have used the UI while the commit is included will have `Name` parameter appended to their configs, not much we can do about it now.

If I didn't cover your concerns, please specify them again, as I might misunderstood.

**Comment by JustArchi** [comment] 2019-03-08 16:20
Oh sorry, you're right 👍

**Closed** 2019-03-30 12:18 UTC
Labels: Bug, Priority: Medium
