### ISSUE TITLE
ASF-ui shows wrong farming info

### ISSUE THREAD

**Issue by JustArchi** [JustArchiNET/ASF-ui#199] opened 2018-12-08 17:43 UTC
![image](https://user-images.githubusercontent.com/1069029/49688876-0adfe680-fb19-11e8-8aae-13d119422a6d.png)

![image](https://user-images.githubusercontent.com/1069029/49688880-1af7c600-fb19-11e8-886e-ccea2b73c30e.png)

It's alright to show `GamesToFarm` above in the overall stats, but ASF explicitly says that `CurrentGamesFarming` is **empty**, so you have wrong logic of treating `GamesToFarm` as currently being played, that's what `CurrentGamesFarming` is for.

**Comment by Aareksio** [comment] 2018-12-08 18:16
What's the output you'd expect?

**Comment by JustArchi** [comment] 2018-12-08 18:16
Top bar with cards, time left and all of that - keep.

Account status - NOT farming (green) if `CurrentGamesFarming` is empty.

**Comment by JustArchi** [comment] 2018-12-08 18:18
In addition to that, it should show the **proper** games being played right now, and not all the `GamesToFarm`. I don't have enough of games to test this but I'm pretty sure that if I had 200 games left to farm, you'd show me 200 game titles on the screenshot above, while the proper way is to show 200 games left to farm in general stats (on the top of the page), but only `CurrentGamesFarming` as the account playing the games. Right now this information is entirely wrong, because my account does **not** play the games you show as "actively idling".

**Comment by Aareksio** [comment] 2018-12-08 18:19
So the problem is the account state being set to `Farming`, correct?

**Comment by JustArchi** [comment] 2018-12-08 18:19
Yes, and the wrong games being displayed.

**Comment by Aareksio** [comment] 2018-12-08 18:21
> Right now this information is entirely wrong, because my account does not play the games you show as "actively idling".

Start playing one of them and check the UI again.

**Comment by JustArchi** [comment] 2018-12-08 18:21
In other words, just because `GamesToFarm` collection is not empty does not mean that account is actively idling - ASF could initialize this property, find out that idling is unavailable and leave it like that, without doing anything else. Such account is **not** farming, and `CurrentGamesFarming` for such account is empty.

**Comment by Aareksio** [comment] 2018-12-08 18:22
We consider the account to be farming because
![screen](https://yko.im/xXIF.png)

**Comment by Aareksio** [comment] 2018-12-08 18:32
![screen](https://yko.im/2Myv.png)

The games are marked as _currently played_ with steam's green outline.
Bots with `CurrentGamesFarming` empty are now shown as `Online` despite having `Paused: false` and `TimeRemaining > 00:00:00`.

**Closed by Aareksio** 2018-12-08 18:32 UTC

**Comment by JustArchi** [comment] 2018-12-08 18:33
![image](https://user-images.githubusercontent.com/1069029/49689336-1682db80-fb20-11e8-9cbb-d3e845581fde.png)

![image](https://user-images.githubusercontent.com/1069029/49689338-1c78bc80-fb20-11e8-8d92-381a9cfa3d03.png)

You have **no** active games being played, no games with green border, yet account **has** green border and stating `Farming`. This is **wrong**, account is **NOT** farming anything right now.

**Comment by JustArchi** [comment] 2018-12-08 18:34
> Bots with CurrentGamesFarming empty are now shown as Online despite having Paused: false and TimeRemaining > 00:00:00.

Thanks!

**Comment by Aareksio** [comment] 2018-12-08 18:34
Hey, don't **bold** me here and read the commit that closed the issue: 04d741b7b268792c508dbc449ef5c899a7d48b29
