### ISSUE TITLE
Error 1006 on quickly switching tabs in ASF-ui

### ISSUE THREAD

**Issue by mrskizzex** [JustArchiNET/ASF-ui#1621] opened 2022-12-28 03:54 UTC
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

5.4.1.8

### ASF-ui version

ec6c5b0

### Bug description

Changing tabs fast, like from Log to Plugins causes 1006 websocket error to pop up.
If you do it slowly and wait for log to load, no error pops up.

### Expected behavior

No error popping up

### Actual behavior

Error pops up 

### Steps to reproduce

Click fast between Log and Plugins tab
https://user-images.githubusercontent.com/11503128/209754519-bfc27563-c7cc-4b7b-bdf0-deb4e9d610b6.mp4

### Can you help us with this bug report?

Somehow, I can test and offer feedback, but can't code

**Comment by JustArchi** [comment] 2022-12-28 04:40
Side note: `1006` is the code that ASF server doesn't (should not) send back to the client, from my fast reproducing of this, it's the web browser aborting the connection, which is fine, but I think the web browser implementation fires `1006` as the final closing code for the web socket, and ASF-ui, as it's coded to just try catch and print everything, shows it as a notification.

The above should be confirmed, but if it's correct, I believe adding if for ignoring `1006` makes sense. On the other hand, we had at least one valid scenario where user was getting `1006` being unable to load the websocket endpoint, so it's not like this code is used only when aborting connection, maybe there is some other indicator that could tell when it's expected 1006 due to closing the socket, and when it's unexpected 1006 due to not being able to make connection.

**Closed** 2022-12-28 22:40 UTC
Labels: 🐛 Bug, 🟢 Low priority
